[package]
name = "rizhi_fu"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
name = "rizhi_fu"
path = "入口.rs"
doctest = false

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "registry"] }
time = { version = "0.3", features = ["local-offset"] }
