[workspace]
resolver = "2"
members = [
    "鸿蒙/基础设施 - 域/识海承载-府",
    "鸿蒙/基础设施 - 域/道术施展-府",
    "鸿蒙/基础设施 - 域/天庭治理-府",
    "鸿蒙/基础设施 - 域/模型连接-府",
    "鸿蒙/基础设施 - 域/日志记录-府",
    "鸿蒙/基础设施 - 域/事件总线-府",
    "鸿蒙/基础设施 - 域/插件承载-府",
    "鸿蒙/世界配置 - 域/配置管理-府",
    "鸿蒙/观测探针-府",
    "乾坤/呈现-域/命令操作-府",
    "证道/鸿蒙 - 域/单元测试-府",
]
