[package]
name = "moxing_fu"
version = "0.1.0"
edition = "2021"

[lib]
name = "moxing_fu"
path = "入口.rs"
doctest = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "2"
peizhi_fu = { path = "../../世界配置 - 域/配置管理-府" }
rizhi_fu = { path = "../日志记录-府" }
jiance_fu = { path = "../../观测探针-府" }
