[package]
name = "hm-desktop"
version.workspace = true
edition.workspace = true

[[bin]]
name = "hm-desktop"
path = "主程序.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
hm-bootstrap = { path = "../../启动入口-府" }
hm-config = { path = "../../../基础能力-域/配置管理-府" }
notify = "6"
tracing = { workspace = true }
