[package]
name = "hm-bootstrap"
version.workspace = true
edition.workspace = true

[lib]

path = "模块.rs"

[[bin]]
name = "hm-bootstrap"
path = "主程序.rs"

[dependencies]
hm-config = { path = "../../基础能力-域/配置管理-府" }
hm-log = { path = "../../基础能力-域/日志管理-府" }
hm-http = { path = "../../基础能力-域/数据服务-府" }
hm-contract = { path = "../../基础契约-域/核心契约-府" }
hm-error = { path = "../../基础契约-域/错误定义-府" }
hm-linkage = { path = "../联动装配-府" }
hm-agent = { path = "../自主开发-府" }
hm-content = { path = "../../基础能力-域/内容生成-府" }
hm-execute = { path = "../../基础能力-域/执行工具-府" }
hm-execute-contract = { path = "../../基础契约-域/执行契约-府" }
hm-cognition = { path = "../../基础能力-域/项目认知-府" }
tc-task = { path = "../../../太初/任务管理-域/任务核心-府" }
tracing = { workspace = true }
ctrlc = "3"
