[package]
name = "jiankong_fu"
version = "0.1.0"
edition = "2021"

[lib]
name = "jiankong_fu"
path = "入口.rs"
doctest = false

[[bin]]
name = "监控"
path = "输出-呈现-殿/路由-挂载-阁/端点-挂载-园/启动.rs"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tower = { version = "0.5", features = ["util"]}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jiance_fu = { path = "../../../鸿蒙/基础设施 - 域/观测探针-府" }
zhuangtai_fu = { path = "../../../鸿蒙/基础设施 - 域/状态共享-府" }
rizhi_fu = { path = "../../../鸿蒙/基础设施 - 域/日志记录-府" }
shihai_fu = { path = "../../../鸿蒙/基础设施 - 域/识海承载-府" }