[package]
name = "hm-execute"
version.workspace = true
edition.workspace = true

[lib]
path = "模块.rs"

[dependencies]
hm-execute-contract = { path = "../../基础契约-域/执行契约-府" }
hm-contract = { path = "../../基础契约-域/核心契约-府" }
hm-error = { path = "../../基础契约-域/错误定义-府" }
glob = "0.3"
tracing = { workspace = true }